name: "Commitlint"

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install commitlint
        run: |
          npm ci
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.js
